libraray_arg:
  max_poly: 6
  max_dt: 1
  max_dx: 6
  use_cross_der: False

Noise:
  sigma_SNR: 0.0    # set to 0.01â€“0.05 to add noise

Subsampling:
  stride_x: 1       # >1 to subsample space
  stride_t: 1       # >1 to subsample time

Dataset_name:
  equation: 'Burgers Equation (viscous)'
  filename: 'burgers_viscous.npy'   # place this file in dataset-Python/

Other_paramters:
  Tau: 0.05
